[package]
name = "sym-exec-tut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = {version="0.11.2", features = ["static-link-z3"], git = "https://github.com/TomMD/z3.rs"}
# lua-kit = "0.1.0"
